#!/usr/bin/env bash
# mise_bootstrap.sh -- Shared helper that makes mise-managed tools
# (erlang, gleam, rebar) visible on PATH without requiring the caller
# to have run `mise activate` in the current shell.
#
# Usage:
#   . scripts/lib/mise_bootstrap.sh   # source from any bash/sh script
#   oaspec_require_tool gleam         # fail fast with a setup message
#
# The sourcing itself runs `oaspec_mise_bootstrap` once, so most
# callers only need the `.` line. The helper is idempotent -- sourcing
# it twice leaves PATH unchanged.

_oaspec_mise_prepend() {
  # Prepend $1 to PATH unless it is already present.
  case ":${PATH-}:" in
    *":$1:"*) ;;
    *) PATH="$1${PATH:+:$PATH}" ;;
  esac
}

# Tools whose parent directory should be added to PATH. `escript` and
# `erl` come with erlang but need to be reachable directly, because
# escripts generated by gleescript use `#!/usr/bin/env escript` and
# resolve the interpreter through PATH, not through mise shims.
_OASPEC_MISE_TOOLS="gleam escript erl rebar3"

oaspec_mise_bootstrap() {
  # ~/.local/bin is the canonical install dir for developer tools
  # that are not managed by mise (e.g. ShellSpec). Keep it on PATH
  # independently of the mise-managed toolchain probe below.
  if [ -n "${HOME:-}" ] && [ -d "$HOME/.local/bin" ]; then
    _oaspec_mise_prepend "$HOME/.local/bin"
  fi

  # Fast path: if the toolchain is already visible, do nothing more.
  # This keeps the helper cheap when the shell has `mise activate`.
  if command -v gleam >/dev/null 2>&1; then
    export PATH
    return 0
  fi

  # Preferred: ask mise for the concrete install-dir of each tool we
  # need. These are absolute paths into ~/.local/share/mise/installs,
  # so they work even when the calling shell is outside a mise project
  # directory and the shims would fail with "no version set".
  if command -v mise >/dev/null 2>&1; then
    local _tool _path
    for _tool in $_OASPEC_MISE_TOOLS; do
      _path="$(mise which "$_tool" 2>/dev/null || true)"
      if [ -n "$_path" ]; then
        _oaspec_mise_prepend "$(dirname "$_path")"
      fi
    done
  fi

  # Fallback: the canonical shim directory. Used when `mise` itself
  # is not on PATH (e.g. a non-standard install) or when `mise which`
  # could not resolve the tools above.
  if ! command -v gleam >/dev/null 2>&1 && [ -n "${HOME:-}" ]; then
    _oaspec_mise_prepend "$HOME/.local/share/mise/shims"
  fi

  export PATH
}

oaspec_require_tool() {
  local _tool="$1"
  if command -v "$_tool" >/dev/null 2>&1; then
    return 0
  fi
  cat >&2 <<EOF
error: required tool '$_tool' was not found on PATH.

This repository manages its toolchain (Erlang, Gleam, rebar3) with
mise. To set up the development environment from a fresh checkout:

    mise install

If mise itself is missing, see https://mise.jdx.dev/getting-started.html.
Alternatively, install '$_tool' by hand and make sure it is on PATH
before running this command.
EOF
  return 127
}

oaspec_mise_bootstrap
