// Code generated by oaspec v0.1.2. DO NOT EDIT.

import gleam/dynamic/decode
import gleam/json
import gleam/option
import api/types

pub fn admin_user_decoder() -> decode.Decoder(types.AdminUser) {
  use id <- decode.field("id", decode.string)
  use name <- decode.field("name", decode.string)
  use permissions <- decode.optional_field("permissions", option.None, decode.optional(decode.list(decode.string)))
  use type <- decode.optional_field("type", option.None, decode.optional(decode.string))
  decode.success(types.AdminUser(id: id, name: name, permissions: permissions, type: type))
}

pub fn decode_admin_user(json_string: String) -> Result(types.AdminUser, json.DecodeError) {
  json.parse(json_string, admin_user_decoder())
}

pub fn admin_user_decoder_list() -> decode.Decoder(List(types.AdminUser)) {
  decode.list(admin_user_decoder())
}

pub fn decode_admin_user_list(json_string: String) -> Result(List(types.AdminUser), json.DecodeError) {
  json.parse(json_string, admin_user_decoder_list())
}

pub fn error_decoder() -> decode.Decoder(types.Error) {
  use code <- decode.field("code", decode.int)
  use details <- decode.optional_field("details", option.None, decode.optional(decode.list(decode.string)))
  use message <- decode.field("message", decode.string)
  decode.success(types.Error(code: code, details: details, message: message))
}

pub fn decode_error(json_string: String) -> Result(types.Error, json.DecodeError) {
  json.parse(json_string, error_decoder())
}

pub fn error_decoder_list() -> decode.Decoder(List(types.Error)) {
  decode.list(error_decoder())
}

pub fn decode_error_list(json_string: String) -> Result(List(types.Error), json.DecodeError) {
  json.parse(json_string, error_decoder_list())
}

pub fn filter_decoder() -> decode.Decoder(types.Filter) {
  use field <- decode.field("field", decode.string)
  use op <- decode.field("op", decode.string)
  decode.success(types.Filter(field: field, op: op))
}

pub fn decode_filter(json_string: String) -> Result(types.Filter, json.DecodeError) {
  json.parse(json_string, filter_decoder())
}

pub fn filter_decoder_list() -> decode.Decoder(List(types.Filter)) {
  decode.list(filter_decoder())
}

pub fn decode_filter_list(json_string: String) -> Result(List(types.Filter), json.DecodeError) {
  json.parse(json_string, filter_decoder_list())
}

pub fn pagination_decoder() -> decode.Decoder(types.Pagination) {
  use page <- decode.optional_field("page", option.None, decode.optional(decode.int))
  use per_page <- decode.optional_field("per_page", option.None, decode.optional(decode.int))
  decode.success(types.Pagination(page: page, per_page: per_page))
}

pub fn decode_pagination(json_string: String) -> Result(types.Pagination, json.DecodeError) {
  json.parse(json_string, pagination_decoder())
}

pub fn pagination_decoder_list() -> decode.Decoder(List(types.Pagination)) {
  decode.list(pagination_decoder())
}

pub fn decode_pagination_list(json_string: String) -> Result(List(types.Pagination), json.DecodeError) {
  json.parse(json_string, pagination_decoder_list())
}

pub fn regular_user_decoder() -> decode.Decoder(types.RegularUser) {
  use id <- decode.field("id", decode.string)
  use name <- decode.field("name", decode.string)
  use subscription <- decode.optional_field("subscription", option.None, decode.string)
  use type <- decode.optional_field("type", option.None, decode.optional(decode.string))
  decode.success(types.RegularUser(id: id, name: name, subscription: subscription, type: type))
}

pub fn decode_regular_user(json_string: String) -> Result(types.RegularUser, json.DecodeError) {
  json.parse(json_string, regular_user_decoder())
}

pub fn regular_user_decoder_list() -> decode.Decoder(List(types.RegularUser)) {
  decode.list(regular_user_decoder())
}

pub fn decode_regular_user_list(json_string: String) -> Result(List(types.RegularUser), json.DecodeError) {
  json.parse(json_string, regular_user_decoder_list())
}

pub fn user_decoder() -> decode.Decoder(types.User) {
  use id <- decode.field("id", decode.string)
  use name <- decode.field("name", decode.string)
  use type <- decode.optional_field("type", option.None, decode.optional(decode.string))
  decode.success(types.User(id: id, name: name, type: type))
}

pub fn decode_user(json_string: String) -> Result(types.User, json.DecodeError) {
  json.parse(json_string, user_decoder())
}

pub fn user_decoder_list() -> decode.Decoder(List(types.User)) {
  decode.list(user_decoder())
}

pub fn decode_user_list(json_string: String) -> Result(List(types.User), json.DecodeError) {
  json.parse(json_string, user_decoder_list())
}

pub fn webhook_event_decoder() -> decode.Decoder(types.WebhookEvent) {
  use callback_url <- decode.field("callbackUrl", decode.string)
  use type <- decode.field("type", decode.string)
  decode.success(types.WebhookEvent(callback_url: callback_url, type: type))
}

pub fn decode_webhook_event(json_string: String) -> Result(types.WebhookEvent, json.DecodeError) {
  json.parse(json_string, webhook_event_decoder())
}

pub fn webhook_event_decoder_list() -> decode.Decoder(List(types.WebhookEvent)) {
  decode.list(webhook_event_decoder())
}

pub fn decode_webhook_event_list(json_string: String) -> Result(List(types.WebhookEvent), json.DecodeError) {
  json.parse(json_string, webhook_event_decoder_list())
}

