// Code generated by oaspec v0.1.2. DO NOT EDIT.

import gleam/json
import api/types

pub fn encode_admin_user_json(value: types.AdminUser) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("name", json.string(value.name)),
    #("permissions", json.nullable(value.permissions, json.string)),
    #("type", json.nullable(value.type, json.string))
  ])
}

pub fn encode_admin_user(value: types.AdminUser) -> String {
  encode_admin_user_json(value) |> json.to_string()
}

pub fn encode_error_json(value: types.Error) -> json.Json {
  json.object([
    #("code", json.int(value.code)),
    #("details", json.nullable(value.details, json.string)),
    #("message", json.string(value.message))
  ])
}

pub fn encode_error(value: types.Error) -> String {
  encode_error_json(value) |> json.to_string()
}

pub fn encode_filter_json(value: types.Filter) -> json.Json {
  json.object([
    #("field", json.string(value.field)),
    #("op", json.string(value.op))
  ])
}

pub fn encode_filter(value: types.Filter) -> String {
  encode_filter_json(value) |> json.to_string()
}

pub fn encode_pagination_json(value: types.Pagination) -> json.Json {
  json.object([
    #("page", json.nullable(value.page, json.int)),
    #("per_page", json.nullable(value.per_page, json.int))
  ])
}

pub fn encode_pagination(value: types.Pagination) -> String {
  encode_pagination_json(value) |> json.to_string()
}

pub fn encode_regular_user_json(value: types.RegularUser) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("name", json.string(value.name)),
    #("subscription", json.nullable(value.subscription, json.string)),
    #("type", json.nullable(value.type, json.string))
  ])
}

pub fn encode_regular_user(value: types.RegularUser) -> String {
  encode_regular_user_json(value) |> json.to_string()
}

pub fn encode_user_json(value: types.User) -> json.Json {
  json.object([
    #("id", json.string(value.id)),
    #("name", json.string(value.name)),
    #("type", json.nullable(value.type, json.string))
  ])
}

pub fn encode_user(value: types.User) -> String {
  encode_user_json(value) |> json.to_string()
}

pub fn encode_webhook_event_json(value: types.WebhookEvent) -> json.Json {
  json.object([
    #("callbackUrl", json.string(value.callback_url)),
    #("type", json.string(value.type))
  ])
}

pub fn encode_webhook_event(value: types.WebhookEvent) -> String {
  encode_webhook_event_json(value) |> json.to_string()
}

