// Code generated by oaspec v0.1.2. DO NOT EDIT.

import gleam/option.{type Option}
import api/types

pub type PostSearchRequest {
  PostSearchRequest(
    body: types.PostSearchRequestBody
  )
}

pub type GetUserRequest {
  GetUserRequest(
    user_id: String
  )
}

pub type PostWebhookRequest {
  PostWebhookRequest(
    body: types.WebhookEvent
  )
}

