// Code generated by oaspec v0.1.2. DO NOT EDIT.

import gleam/option.{type Option}

pub type AdminUserType {
  AdminUserTypeAdmin
  AdminUserTypeRegular
}

pub type FilterOp {
  FilterOpEq
  FilterOpNe
  FilterOpGt
  FilterOpLt
}

pub type RegularUserType {
  RegularUserTypeAdmin
  RegularUserTypeRegular
}

pub type UserType {
  UserTypeAdmin
  UserTypeRegular
}

pub type AdminUser {
  AdminUser(
    id: String,
    name: String,
    permissions: Option(List(String)),
    type: Option(AdminUserType)
  )
}

pub type Error {
  Error(
    code: Int,
    details: Option(List(String)),
    message: String
  )
}

pub type Filter {
  Filter(
    field: String,
    op: FilterOp
  )
}

pub type Pagination {
  Pagination(
    page: Option(Int),
    per_page: Option(Int)
  )
}

pub type RegularUser {
  RegularUser(
    id: String,
    name: String,
    subscription: Option(String),
    type: Option(RegularUserType)
  )
}

pub type User {
  User(
    id: String,
    name: String,
    type: Option(UserType)
  )
}

pub type WebhookEvent {
  WebhookEvent(
    callback_url: String,
    type: String
  )
}

pub type PostSearchResponseOk {
  PostSearchResponseOk(
    results: Option(List(User)),
    total: Option(Int)
  )
}

pub type PostSearchRequestBody {
  PostSearchRequestBody(
    filters: Option(List(Filter)),
    page: Option(Int),
    per_page: Option(Int),
    query: Option(String)
  )
}

pub type GetUserResponseOk {
  GetUserResponseOkAdminUser(AdminUser)
  GetUserResponseOkRegularUser(RegularUser)
}

